title: Juan Alejandro Morais
email: timrodz@icloud.com
description: This is my personal blog! Here I write about things in life and everything related to game development.
permalink: ':title/'
baseurl: "/blog"
url: "https://Mad-Hyrax.github.io"

# Author settings
author: Juan Alejandro Morais
author-pic: headshot.jpeg
about-author: Juan Rodriguez is a programmer and game developer focusing on game feel and UI/UX.

# Contact links
email: timrodz@icloud.com
# phone: # Add your Phone number
website: http://timrodz.com
linkedin: timrodz
github: timrodz
twitter: '@timrodz'
# facebook: # Add your Facebook handle
instagram: timrodz
# pinterest: # Add your Pinterest handle

# Newsletter
# mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: timrodz

# Tracker
# analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
